# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('theme_file', models.FileField(null=True, upload_to='themes_archives')),
                ('sites', models.ManyToManyField(blank=True, null=True, to='sites.Site')),
            ],
            options={
                'verbose_name_plural': 'Themes',
                'verbose_name': 'Theme',
            },
        ),
    ]
